import type { Metadata } from "next";
import "./styles/globals.css";
import Header from "./components/header"; // Adjust the import path as needed
import Footer from "./components/footer"; // Adjust the import path as needed
import Link from 'next/link';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
